name: Maven JUnit

on: push

jobs:

  job:
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 8, 11, 17 ]
      fail-fast: true

    steps:

      - name: Git
        uses: actions/checkout@v3

      - name: Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          check-latest: true
          cache: 'maven'

      - name: Test
        run: mvn --batch-mode --show-version --errors test --file pom.xml
